# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: nixfmt
        name: nixfmt
        language: system
        entry: nixfmt
        files: \.nix$

    -   id: go-test
        name: Go Test
        language: system
        entry: go test ./...
        files: \.go$
        pass_filenames: false
